set(CMAKE_PREFIX_PATH ${CMAKE_CURRENT_LIST_DIR} CACHE PATH "")

# BOOST config
set(BOOST_ROOT ${CMAKE_CURRENT_LIST_DIR} CACHE PATH "")
set(BOOST_INCLUDEDIR ${BOOST_ROOT}/include/boost-1_61 CACHE PATH "")
set(BOOST_LIBRARYDIR ${BOOST_ROOT}/lib CACHE PATH "")
set(Boost_USE_MULTITHREADED ON CACHE BOOL "")
set(Boost_USE_STATIC_LIBS OFF CACHE BOOL "")
set(Boost_USE_STATIC_RUNTIME OFF CACHE BOOL "")


# GFLAGS config
set(GFLAGS_DIR ${CMAKE_CURRENT_LIST_DIR}/cmake CACHE PATH "")
set(gflags_DIR ${CMAKE_CURRENT_LIST_DIR}/cmake  CACHE PATH "")
set(GFlags_DIR ${CMAKE_CURRENT_LIST_DIR}/cmake  CACHE PATH "")
set(Gflags_DIR ${CMAKE_CURRENT_LIST_DIR}/cmake  CACHE PATH "")


# GLOG config
set(GLOG_DIR ${CMAKE_CURRENT_LIST_DIR}/lib/cmake/glog CACHE PATH "")
set(glog_DIR ${CMAKE_CURRENT_LIST_DIR}/lib/cmake/glog CACHE PATH "")
set(Glog_DIR ${CMAKE_CURRENT_LIST_DIR}/cmake  CACHE PATH "")


# HDF5 config
set(HDF5_DIR ${CMAKE_CURRENT_LIST_DIR}/cmake CACHE PATH "")
set(hdf5_DIR ${CMAKE_CURRENT_LIST_DIR}/cmake CACHE PATH "")
set(HDF5_ROOT_DIR ${CMAKE_CURRENT_LIST_DIR}/cmake CACHE PATH "")


# LEVELDB config
set(LEVELDB_DIR ${CMAKE_CURRENT_LIST_DIR}/cmake CACHE PATH "")
set(leveldb_DIR ${CMAKE_CURRENT_LIST_DIR}/cmake  CACHE PATH "")
set(LevelDB_DIR ${CMAKE_CURRENT_LIST_DIR}/cmake  CACHE PATH "")


# LMDB config
set(LMDB_DIR ${CMAKE_CURRENT_LIST_DIR}/cmake CACHE PATH "")
set(lmdb_DIR ${CMAKE_CURRENT_LIST_DIR}/cmake  CACHE PATH "")


# OPENBLAS config
set(OPENBLAS_INCLUDE_DIR ${CMAKE_CURRENT_LIST_DIR}/include CACHE PATH "")
set(openblas_INCLUDE_DIR ${CMAKE_CURRENT_LIST_DIR}/include CACHE PATH "")
set(OpenBLAS_INCLUDE_DIR ${CMAKE_CURRENT_LIST_DIR}/include CACHE PATH "")
set(OPENBLAS_LIB ${CMAKE_CURRENT_LIST_DIR}/lib/libopenblas.dll.a CACHE FILEPATH "")
set(openblas_LIB ${CMAKE_CURRENT_LIST_DIR}/lib/libopenblas.dll.a CACHE FILEPATH "")
set(OpenBLAS_LIB ${CMAKE_CURRENT_LIST_DIR}/lib/libopenblas.dll.a CACHE FILEPATH "")


# OPENCV config
set(OPENCV_DIR ${CMAKE_CURRENT_LIST_DIR}  CACHE PATH "")
set(opencv_DIR ${CMAKE_CURRENT_LIST_DIR}  CACHE PATH "")
set(OpenCV_DIR ${CMAKE_CURRENT_LIST_DIR}  CACHE PATH "")
set(OpenCV_STATIC OFF CACHE BOOL "")


# PROTOBUF config
set(PROTOBUF_DIR ${CMAKE_CURRENT_LIST_DIR}/cmake CACHE PATH "")
set(protobuf_DIR ${CMAKE_CURRENT_LIST_DIR}/cmake CACHE PATH "")
set(Protobuf_DIR ${CMAKE_CURRENT_LIST_DIR}/cmake CACHE PATH "")
set(protobuf_MODULE_COMPATIBLE ON CACHE BOOL "")


# SNAPPY config
set(SNAPPY_DIR ${CMAKE_CURRENT_LIST_DIR}/cmake)
set(snappy_DIR ${CMAKE_CURRENT_LIST_DIR}/cmake)


# ZLIB config
set(ZLIB_INCLUDE_DIR ${CMAKE_CURRENT_LIST_DIR}/include CACHE PATH "")
set(ZLIB_LIBRARY_DEBUG  ${CMAKE_CURRENT_LIST_DIR}/lib/caffezlibd.lib CACHE FILEPATH "")
set(ZLIB_LIBRARY_RELEASE  ${CMAKE_CURRENT_LIST_DIR}/lib/caffezlib.lib CACHE FILEPATH "")

